### ISSUE TITLE
Nav items are not clickable when scrolled down completely

### ISSUE THREAD

**Issue by paulschuberth** [garritfra/garrit.xyz#88]
**Steps to reproduce**
 1. Go to https://garrit.xyz
 2. Make sure browser window is wider than 1000px
 ~~3. scroll completely down.~~
 3. Scroll to a position where are "Skill Category Headline" alines itself with the navlinks.
 4. try to click ;)

**Comment by paulschuberth** [comment]
Turns out it does depend on the position the website is scrolled to. In certain scroll positions the the navlinks are blocked by a headline. This causes the links not being clickable.
<img width="1792" alt="Screenshot 2021-01-05 at 21 49 10" src="https://user-images.githubusercontent.com/14339594/103697383-26d83f80-4fa0-11eb-992c-9b42c6365ef0.png">

**Comment by garritfra** [comment]
@paulschuberth oh, das hab ich gar nicht gesehen! Ich muss irgendwann das Repo "entwatched" haben.😅 Die Website braucht demnächst generell etwas liebe. Danke fürs melden!

**Comment by paulschuberth** [comment]
Klaro, immer gerne 😉

**Comment by garritfra** [comment]
Fixed during redesign! 🙂
